// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniWebApp.Data;

namespace UniWebApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190530110545_fixRelationCascade")]
    partial class fixRelationCascade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("UniWebApp.Core.AppEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("AppEntities");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("EntityId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Section")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("AppEntityFields");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AppEntityDataField");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataFieldComboboxOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ComboboxId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ComboboxId");

                    b.ToTable("AppEntityDataFieldComboboxOptions");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("EntityId");

                    b.Property<int>("relatedEntityId");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("AppEntityRelations");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AppEntityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pessoa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pessoa Coletiva"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Empresa"
                        });
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataFieldBoolean", b =>
                {
                    b.HasBaseType("UniWebApp.Core.AppEntityDataField");

                    b.Property<bool>("Value");

                    b.HasDiscriminator().HasValue("AppEntityDataFieldBoolean");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataFieldCombobox", b =>
                {
                    b.HasBaseType("UniWebApp.Core.AppEntityDataField");

                    b.Property<int>("SelectedOption");

                    b.HasDiscriminator().HasValue("AppEntityDataFieldCombobox");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataFieldDate", b =>
                {
                    b.HasBaseType("UniWebApp.Core.AppEntityDataField");

                    b.Property<DateTime>("Value")
                        .HasColumnName("AppEntityDataFieldDate_Value");

                    b.HasDiscriminator().HasValue("AppEntityDataFieldDate");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataFieldNumber", b =>
                {
                    b.HasBaseType("UniWebApp.Core.AppEntityDataField");

                    b.Property<decimal>("Value")
                        .HasColumnName("AppEntityDataFieldNumber_Value");

                    b.HasDiscriminator().HasValue("AppEntityDataFieldNumber");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataFieldText", b =>
                {
                    b.HasBaseType("UniWebApp.Core.AppEntityDataField");

                    b.Property<string>("Value")
                        .HasColumnName("AppEntityDataFieldText_Value");

                    b.HasDiscriminator().HasValue("AppEntityDataFieldText");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntity", b =>
                {
                    b.HasOne("UniWebApp.Core.AppEntityType", "Type")
                        .WithMany("Entities")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataField", b =>
                {
                    b.HasOne("UniWebApp.Core.AppEntity", "Entity")
                        .WithMany("Fields")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityDataFieldComboboxOption", b =>
                {
                    b.HasOne("UniWebApp.Core.AppEntityDataFieldCombobox", "Combobox")
                        .WithMany("Options")
                        .HasForeignKey("ComboboxId");
                });

            modelBuilder.Entity("UniWebApp.Core.AppEntityRelation", b =>
                {
                    b.HasOne("UniWebApp.Core.AppEntity", "Entity")
                        .WithMany("Relations")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
